export const DocumentTypes = {
  PersonalDetails: "personal_details",
  Passport: "passport",
  DriverLicense: "driver_license",
  IdentityCard: "identity_card",
  InternalPassport: "internal_passport",
  Address: "address",
  UtilityBill: "utility_bill",
  BankStatement: "bank_statement",
  RentalAgreement: "rental_agreement",
  PassportRegistration: "passport_registration",
  TemporaryRegistration: "temporary_registration",
  PhoneNumber: "phone_number",
  Email: "email",
};
