export const TelegramIntentBits = {
  Message: "message",
  EditedMessage: "edited_message",
  ChannelPost: "channel_post",
  EditedChannelPost: "edited_channel_post",
  InlineQuery: "inline_query",
  ChosenInlineResult: "chosen_inline_result",
  CallbackQuery: "callback_query",
  ShippingQuery: "shipping_query",
  PreCheckoutQuery: "pre_checkout_query",
  Poll: "poll",
  PollAnswer: "poll_answer",
  MyChatMember: "my_chat_member",
  ChatMember: "chat_member",
  ChatJoinRequest: "chat_join_request",
};
