export const TelegramBot: typeof import("./TelegramBot");
export const BaseClient: typeof import("./BaseClient");
export const SimpleStorage: typeof import("./session/SimpleStorage");
export const CashSession: typeof import("./session/CashSession");
export const SessionTypes: typeof import("./session/SessionTypes");
export const Request: typeof import("./request");
export const Collection: typeof import("@telegram.ts/collection").Collection;
export const Search: typeof import("@telegram.ts/documentation").Search;
export const Markup: typeof import("./replyMarkup/Markup");
export const Keyboard: typeof import("./replyMarkup/Keyboard");
export const MessageCollector: typeof import("./MessageCollector");
export const Events: any;
export const ChatActionType: any;
export const EntityType: typeof import("./constanta/EntityType");
export const QueryString: typeof import("./constanta/QueryString");
export const ChatPermission: any;
export const GroupPermission: any;
export const GroupStatus: typeof import("./constanta/GroupStatus");
export const DocumentTypes: typeof import("./constanta/DocumentTypes");
export const IntentsBitField: typeof import("./IntentsBitField").IntentsBitField;
export const IntentBits: any;
export const TelegramIntentBits: any;
export const decodeIntents: typeof import("./IntentsBitField").decodeIntents;
export const html: typeof import("@telegram.ts/formatters/dist/html");
export const markdownv: typeof import("@telegram.ts/formatters/dist/markdownv");
export const checkMessageLinks: typeof import("./Util").checkMessageLinks;
export const extractUserMentions: typeof import("./Util").extractUserMentions;
export const extractHashtags: typeof import("./Util").extractHashtags;
export const checkLocation: typeof import("./Util").checkLocation;
export const checkUserMentions: typeof import("./Util").checkUserMentions;
export const checkHashtags: typeof import("./Util").checkHashtags;
export const checkPhoneNumber: typeof import("./Util").checkPhoneNumber;
export const extractUserIdFromLink: typeof import("./Util").extractUserIdFromLink;
export const checkGroupOrChannel: typeof import("./Util").checkGroupOrChannel;
export const checkEmoji: typeof import("./Util").checkEmoji;
export const checkSticker: typeof import("./Util").checkSticker;
export const extractUsernameFromLink: typeof import("./Util").extractUsernameFromLink;
export const checkBot: typeof import("./Util").checkBot;
export const checkChannel: typeof import("./Util").checkChannel;
export const checkLink: typeof import("./Util").checkLink;
export const checkGroup: typeof import("./Util").checkGroup;
export const checkUsername: typeof import("./Util").checkUsername;
export const extractUsername: typeof import("./Util").extractUsername;
export const version: any;
